### ISSUE TITLE
.spk群晖718无法安装

### ISSUE THREAD

**Issue by kingswon** [koolshare/synology-easyexplorer#1]
.spk文件在群晖套件里无法手动安装 提示不支持或与DSM版本不兼容
型号DS718+  CPU intel celeron j3455  DSM6.1.4

**Comment by jannson** [comment]
现在可以了吗？最新版本。

**Comment by kingswon** [comment]
还是不行 0.1.4还是不能安装

**Comment by jannson** [comment]
重新下载安装，便可以支持。
并请尝试我们的 iOS APP
