### ISSUE TITLE
群晖ds214play安装以后，一直是停用状态，无法启动服务。

### ISSUE THREAD

**Issue by delpyh** [koolshare/synology-easyexplorer#3]
您好，

我在ds214play安装以后，无法启用服务，请问该如何处理？

谢谢。

**Comment by jannson** [comment]
试试这个地址：https://github.com/koolshare/synology-easyexplorer/blob/master/easyexplorer_arm.spk

**Comment by jannson** [comment]
APP 已出，请尝试使用。
