### ISSUE TITLE
群辉918无法安装

### ISSUE THREAD

**Issue by chen010311** [koolshare/synology-easyexplorer#5]
DSM 6.21 安装的时候提示此套件在DSM平台上不支持 或与当前的DSM版本不兼容

**Comment by miniers** [comment]
自己打包即可，下载后修改INFO文件 ，在arch中添加  apollolake  然后打包就好了

**Comment by jannson** [comment]
@miniers 能否加群，我请求下，写成什么样子？？？
https://github.com/koolshare/ddnsto/blob/master/doc/easy-explorer.md

这个链接最底下有一个二维码，可以加入。

**Comment by jannson** [comment]
或者帮我 提一个 pr 也行。感谢。

**Comment by jannson** [comment]
借助一些关键词，找到了这个：https://www.synology.com/en-global/knowledgebase/DSM/tutorial/Compatibility_Peripherals/What_kind_of_CPU_does_my_NAS_have

我试试改弄两个版本试试。

**Comment by miniers** [comment]
提了个PR #6 😃

**Comment by jannson** [comment]
https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model
这个表更好。
